language: java
jdk:
  - oraclejdk8
notifications:
  email:
    - Alejandro.Ruiz@jalasoft.com
    - Marco.Cadima@jalasoft.com
    - Jimmy.Rojas@jalasoft.com
    - Dan.Canqui@jalasoft.com
    - Fernando.Hurtado@jalasoft.com
script: "mvn test"
before_deploy: "echo 'ready?'"
deploy:
	provider: bintray
	file: "descriptor.json"
	user: "$System.env.BINTRAY_USER_NAME"
	key: "$System.evn.BINTRAY_API_KEY"
	
	

