language: java
jdk:
  - oraclejdk8
notifications:
  email:
    - Alejandro.Ruiz@jalasoft.com
    - Marco.Cadima@jalasoft.com
    - Jimmy.Rojas@jalasoft.com
    - Dan.Canqui@jalasoft.com
    - Fernando.Hurtado@jalasoft.com
script: "ls"
script: "cd enforce-sonarqube-plugin/sonar-apex-plugin/target"
script: "mvn test"
script: "mvn package"
before_deploy: "echo 'ready?'"
deploy:
    provider: bintray
    file: "descriptor.json"
    user: $BINTRAY_USER_NAME
    key: $BINTRAY_API_KEY
