language: java
jdk:
  - oraclejdk8
notifications:
  email:
    - Alejandro.Ruiz@jalasoft.com
    - Marco.Cadima@jalasoft.com
    - Jimmy.Rojas@jalasoft.com
    - Dan.Canqui@jalasoft.com
    - Fernando.Hurtado@jalasoft.com
script: "mvn test"
before_deploy: "echo 'ready?'"
deploy:
    provider: bintray
    file: "descriptor.json"
    user: "kevintveizaga"
    key: "93abe9a30a305fa115ba364d831fc33f114e0cc5"
    on: develop
